sudo: required

services:
    - docker

before_install:
    - docker build -t ajaykotapati23/loginapp .

script:
    #docker login
    - docker run ajaykotapati23/loginapp npm test

after_success:
    #push after test
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push ajaykotapati23/loginapp