sudo: required

services:
    - docker

before_install:
    - docker build -t softwarebhayya/loginapp .

script:
    - docker run softwarebhayya/loginapp npm test

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push softwarebhayya/loginapp